"""
Create an inventory of all raw FASTA records and export their metadata and
sequences to a formatted Excel workbook.

What the script does
--------------------
1. Recursively searches the ``01_RawData`` directory for supported FASTA files.
2. Reads every FASTA record using Biopython.
3. Derives a readable virus or variant name from the parent folder name.
4. Extracts an accession identifier from the FASTA header when possible.
5. Removes whitespace from sequences and calculates their ungapped lengths.
6. Generates an MD5 hash from each ungapped sequence for duplicate checking.
7. Creates a standardized FASTA identifier in the form ``virus|accession``.
8. Writes the complete inventory, including the original sequence, to Excel.

Inputs
------
Directory:
    ``01_RawData`` located in the same directory as this script.

Supported file extensions:
    ``.fasta``, ``.fa``, ``.faa``, ``.fna``, and ``.fas``.

Expected organization:
    FASTA files may be stored directly in ``01_RawData`` or in nested folders.
    The immediate parent folder name is used as the source category and is
    converted to a display name through ``DISPLAY_NAME_MAP`` when available.

Outputs
-------
Directory:
    ``02_CuratedRawData`` located in the same directory as this script.

Excel workbook:
    ``raw_fasta_inventory_with_sequences.xlsx``

The workbook contains the source folder and file, original FASTA identifiers,
accession information, sequence length, sequence hash, curated FASTA ID,
original description, and full sequence for every successfully read record.

Required packages
-----------------
    biopython
    openpyxl
"""

from pathlib import Path
import hashlib
import re

from Bio import SeqIO


# =========================================================
# Paths
# =========================================================

# Directory containing this Python script. All input and output paths are
# defined relative to this location so that the workflow remains portable.
BASE_DIR = Path(__file__).resolve().parent

# Input directory containing raw FASTA files, including files in subfolders.
RAW_DIR = BASE_DIR / "01_RawData"

# Output directory and Excel workbook generated by this script.
OUTPUT_DIR = BASE_DIR / "02_CuratedRawData"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_EXCEL = OUTPUT_DIR / "raw_fasta_inventory_with_sequences.xlsx"


# =========================================================
# FASTA extensions
# =========================================================

# File extensions recognized as FASTA-formatted sequence files.
FASTA_EXTENSIONS = [".fasta", ".fa", ".faa", ".fna", ".fas"]


# =========================================================
# Folder name display mapping
# =========================================================

# Converts folder-safe names into publication-friendly virus or variant names.
# Folder names not included here are retained unchanged.
DISPLAY_NAME_MAP = {
    "Alpha": "Alpha",
    "Beta": "Beta",
    "Delta": "Delta",
    "Omicron_BA1": "Omicron BA.1",
    "Omicron_BA2": "Omicron BA.2",
    "Omicron_XBB": "Omicron XBB",
    "SARS_CoV_2": "SARS-CoV-2",
    "SARS_CoV": "SARS-CoV",
    "MERS_CoV": "MERS-CoV",
    "Wuhan_RefSeq": "Wuhan",
    "Bat_CoV": "Bat-CoV",
    "H229E": "HCoV-229E",
    "HKU1": "HCoV-HKU1",
    "OC43": "HCoV-OC43",
    "NL63": "HCoV-NL63",
}


# =========================================================
# Helper functions
# =========================================================

def clean_for_fasta_id(text):
    """Convert text into a safe component of a FASTA identifier.

    Input
    -----
    text : Any
        Text such as a virus name, accession, or original record identifier.

    Output
    ------
    str
        Cleaned text in which spaces and selected punctuation are replaced by
        underscores. Repeated underscores and leading or trailing underscores
        are removed.
    """
    text = str(text).strip()

    for ch in [" ", "/", "\\", "|", ":", ";", ",", "(", ")", "[", "]", "{", "}"]:
        text = text.replace(ch, "_")

    while "__" in text:
        text = text.replace("__", "_")

    return text.strip("_")


def get_virus_name_from_folder(folder_name):
    """Return a readable virus or variant name for a source folder.

    Input
    -----
    folder_name : str
        Name of the folder containing a FASTA file.

    Output
    ------
    str
        Mapped display name when the folder exists in ``DISPLAY_NAME_MAP``;
        otherwise, the original folder name.
    """
    return DISPLAY_NAME_MAP.get(folder_name, folder_name)


def get_accession(record):
    """Extract an accession-like identifier from a Biopython FASTA record.

    The function first checks pipe-delimited record IDs. If no suitable value
    is found, it searches the record ID and description using common accession
    patterns. The cleaned original record ID is used as a final fallback.

    Input
    -----
    record : Bio.SeqRecord.SeqRecord
        FASTA record returned by ``Bio.SeqIO.parse``.

    Output
    ------
    str
        Extracted accession or a cleaned fallback identifier.
    """
    raw_id = str(record.id)

    if "|" in raw_id:
        parts = raw_id.split("|")
        for part in reversed(parts):
            part = part.strip()
            if part:
                return part

    text = f"{record.id} {record.description}"

    patterns = [
        r"YP_\d+\.\d+",
        r"NP_\d+\.\d+",
        r"NC_\d+\.\d+",
        r"[A-Z]{2,4}_?\d{5,}\.?\d*",
        r"[A-Z]{3}\d{5,}\.?\d*",
    ]

    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            return match.group(0)

    return clean_for_fasta_id(raw_id)


def sequence_hash(sequence):
    """Calculate an MD5 hash for a normalized, ungapped sequence.

    Input
    -----
    sequence : str or sequence-like object
        Amino acid or nucleotide sequence. Letter case, whitespace, and gap
        characters do not influence the resulting hash.

    Output
    ------
    str
        A 32-character hexadecimal MD5 digest that can be used to identify
        exact duplicate sequences.
    """
    sequence = str(sequence).upper()
    sequence = sequence.replace("-", "")
    sequence = sequence.replace(" ", "")
    sequence = sequence.replace("\n", "")
    sequence = sequence.replace("\r", "")

    return hashlib.md5(sequence.encode("utf-8")).hexdigest()


def get_fasta_files(raw_dir):
    """Recursively identify supported FASTA files in an input directory.

    Input
    -----
    raw_dir : pathlib.Path
        Root directory to search.

    Output
    ------
    list[pathlib.Path]
        Alphabetically sorted paths of all files whose extensions match
        ``FASTA_EXTENSIONS``.
    """
    fasta_files = []

    for path in raw_dir.rglob("*"):
        if path.is_file() and path.suffix.lower() in FASTA_EXTENSIONS:
            fasta_files.append(path)

    return sorted(fasta_files)


def read_fasta_records(fasta_file):
    """Read all records from one FASTA file.

    Input
    -----
    fasta_file : pathlib.Path
        Path to a FASTA-formatted file.

    Output
    ------
    list[Bio.SeqRecord.SeqRecord]
        Parsed records. An empty list is returned when the file cannot be read,
        and the corresponding error is printed to the console.
    """
    try:
        return list(SeqIO.parse(str(fasta_file), "fasta"))
    except Exception as e:
        print(f"\nWarning. Could not read file: {fasta_file}")
        print(f"  Error: {e}")
        return []


def create_excel(rows):
    """Write the FASTA inventory to a formatted Excel workbook.

    Input
    -----
    rows : list[dict]
        One dictionary per FASTA record. Each dictionary must contain all
        column names defined in the local ``columns`` list.

    Output
    ------
    None
        The function saves ``raw_fasta_inventory_with_sequences.xlsx`` to
        ``OUTPUT_DIR``. If ``rows`` is empty, the workbook contains a single
        message stating that no FASTA records were found.
    """
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils import get_column_letter
    except ImportError:
        raise ImportError(
            "openpyxl is not installed. Install it using:\n"
            "pip install openpyxl"
        )

    wb = Workbook()
    ws = wb.active
    ws.title = "Raw FASTA inventory"

    if not rows:
        ws["A1"] = "No FASTA records found."
        wb.save(OUTPUT_EXCEL)
        return

    columns = [
        "Virus or variant",
        "Source folder",
        "Source file name",
        "Original FASTA ID",
        "Accession or naming",
        "Sequence length",
        "Sequence hash",
        "Curated FASTA ID",
        "Original description",
        "Sequence",
    ]

    # Define consistent formatting for the header and data cells.
    header_fill = PatternFill("solid", fgColor="1F4E79")
    header_font = Font(bold=True, color="FFFFFF")
    thin = Side(style="thin", color="D9D9D9")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    # Write and format the column headers.
    for col_idx, col_name in enumerate(columns, start=1):
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = border

    # Write all FASTA inventory records to the worksheet.
    for row_idx, row in enumerate(rows, start=2):
        for col_idx, col_name in enumerate(columns, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=row[col_name])
            cell.border = border

            if col_name == "Sequence":
                cell.alignment = Alignment(horizontal="left", vertical="top", wrap_text=False)
            else:
                cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=False)

    # Keep the header visible and enable filtering for all populated columns.
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    # Assign readable widths according to the expected content of each column.
    column_widths = {
        "Virus or variant": 20,
        "Source folder": 20,
        "Source file name": 35,
        "Original FASTA ID": 35,
        "Accession or naming": 22,
        "Sequence length": 16,
        "Sequence hash": 36,
        "Curated FASTA ID": 45,
        "Original description": 60,
        "Sequence": 100,
    }

    for col_idx, col_name in enumerate(columns, start=1):
        col_letter = get_column_letter(col_idx)
        ws.column_dimensions[col_letter].width = column_widths.get(col_name, 20)

    ws.row_dimensions[1].height = 28

    wb.save(OUTPUT_EXCEL)


# =========================================================
# Main
# =========================================================

def main():
    """Run the complete raw FASTA inventory workflow.

    Input
    -----
    None
        The function uses the predefined ``RAW_DIR`` and related global paths.

    Output
    ------
    None
        Creates the Excel inventory at ``OUTPUT_EXCEL`` and prints the files
        processed, record counts, output path, and total number of records.

    Raises
    ------
    FileNotFoundError
        If ``01_RawData`` does not exist or contains no supported FASTA files.
    """
    if not RAW_DIR.exists():
        raise FileNotFoundError(f"Raw folder not found:\n{RAW_DIR}")

    fasta_files = get_fasta_files(RAW_DIR)

    if not fasta_files:
        raise FileNotFoundError(f"No FASTA files were found inside:\n{RAW_DIR}")

    print("\nFound FASTA files:")
    for fasta_file in fasta_files:
        print(f"  {fasta_file.relative_to(BASE_DIR)}")

    rows = []

    # Process each FASTA file independently and append one output row per record.
    for fasta_file in fasta_files:
        source_folder = fasta_file.parent.name
        source_file_name = fasta_file.name
        virus_name = get_virus_name_from_folder(source_folder)

        records = read_fasta_records(fasta_file)

        print(f"\nReading: {fasta_file.relative_to(BASE_DIR)}")
        print(f"  Virus or variant: {virus_name}")
        print(f"  Records: {len(records)}")

        for record in records:
            # Normalize sequence text while retaining alignment gaps in the
            # sequence exported to Excel.
            sequence = str(record.seq).upper()
            sequence = sequence.replace(" ", "")
            sequence = sequence.replace("\n", "")
            sequence = sequence.replace("\r", "")

            # Use the ungapped sequence for length measurement and hashing.
            sequence_no_gaps = sequence.replace("-", "")
            seq_len = len(sequence_no_gaps)
            seq_hash = sequence_hash(sequence)

            accession = get_accession(record)

            # Construct a consistent identifier suitable for later curated
            # FASTA exports, phylogenetic analysis, or sequence comparison.
            curated_fasta_id = (
                f"{clean_for_fasta_id(virus_name)}|"
                f"{clean_for_fasta_id(accession)}"
            )

            rows.append({
                "Virus or variant": virus_name,
                "Source folder": source_folder,
                "Source file name": source_file_name,
                "Original FASTA ID": record.id,
                "Accession or naming": accession,
                "Sequence length": seq_len,
                "Sequence hash": seq_hash,
                "Curated FASTA ID": curated_fasta_id,
                "Original description": record.description,
                "Sequence": sequence,
            })

    create_excel(rows)

    print("\nExcel file created successfully:")
    print(f"  {OUTPUT_EXCEL}")
    print(f"\nTotal records written: {len(rows)}")


# Execute the workflow only when this file is run directly. Importing the file
# as a module will not automatically process the FASTA data.
if __name__ == "__main__":
    main()
