"""
Figure 5D: Residue overlap map for ACE2 interface, variant mutation, and high NSI.

Code developed by
-----------------
Nitish Katoch

Purpose
-------
This script identifies selected SARS-CoV-2 spike residues that simultaneously
relate to ACE2 binding, variant-specific amino acid mutations, and elevated
Nitrosative Susceptibility Index (NSI). It summarizes these features in a
residue-level table and generates a publication-style categorical overlap map.

Input
-----
03_Results/Figure4_delta_NSI_vs_Wuhan.csv

The input table must contain the following columns:
    Group
    Variant
    Position
    Reference_AA
    Variant_consensus_AA
    Residue_change
    Smoothed_NSI
    Delta_NSI_vs_Wuhan

Main calculations
-----------------
1. Selects predefined spike residues of biological interest.
2. Classifies each residue as a direct ACE2-interface residue, a near-interface
   residue, or a non-interface residue.
3. Detects whether the consensus amino acid differs from the Wuhan reference in
   Alpha, Beta, Delta, or Omicron BA.2.
4. Marks a residue as high NSI when its smoothed NSI is greater than or equal to
   HIGH_NSI_THRESHOLD.
5. Calculates the maximum NSI, mean delta NSI, and maximum delta NSI across
   non-Wuhan variants for each selected residue.
6. Exports the complete residue-level summary table.

Plot generated
--------------
A categorical heatmap-like overlap map with rows representing selected residues
and columns representing:
    ACE2 interface status
    Variant mutation status
    High NSI status

Each cell is labelled Yes, Near, or No. Functional interpretations are shown to
the right of the matrix.

Outputs
-------
03_Results/Figure5D_residue_overlap_map.png
    High-resolution raster figure.

03_Results/Figure5D_residue_overlap_map.pdf
    Vector-format publication figure.

03_Results/Figure5D_residue_overlap_table.csv
    Residue-level interface, mutation, NSI, delta NSI, and interpretation table.

Dependencies
------------
Python 3, pandas, NumPy, and Matplotlib.

Notes
-----
The script does not calculate NSI from sequence data. It uses the position-wise
NSI and delta NSI values previously generated by the Figure 4 analysis.
"""
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle


# =========================================================
# Figure 5D
# Contact/residue overlap map
# ACE2-interface residue + variant mutation + high-NSI residue
# =========================================================

BASE_DIR = Path(__file__).resolve().parent

INPUT_CSV = BASE_DIR / "03_Results" / "Figure4_delta_NSI_vs_Wuhan.csv"

OUTPUT_DIR = BASE_DIR / "03_Results"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_PNG = OUTPUT_DIR / "Figure5D_residue_overlap_map.png"
OUTPUT_PDF = OUTPUT_DIR / "Figure5D_residue_overlap_map.pdf"
OUTPUT_TABLE = OUTPUT_DIR / "Figure5D_residue_overlap_table.csv"


# =========================================================
# Residues to summarize
# =========================================================

RESIDUE_ORDER = [
    417,
    449,
    453,
    478,
    484,
    489,
    493,
    498,
    501,
    505,
]

ACE2_DIRECT_INTERFACE = {
    417, 449, 453, 455, 456, 475, 486, 487, 489, 493, 498, 501, 505
}

ACE2_NEAR_INTERFACE = {
    477, 478, 484
}

# Residue-level interpretation for manuscript figure.
IMPORTANCE = {
    417: "Interface mutation; charge/polarity change",
    449: "ACE2-interface tyrosine",
    453: "ACE2-interface tyrosine",
    478: "Near-interface BA.2 mutation",
    484: "Near-interface BA.2 mutation",
    489: "ACE2-interface tyrosine",
    493: "Interface mutation",
    498: "Interface mutation",
    501: "Interface mutation; tyrosine gained",
    505: "Interface mutation; tyrosine lost in BA.2",
}

VARIANT_DISPLAY = {
    "Wuhan": "Wuhan",
    "Alpha": "Alpha",
    "Beta": "Beta",
    "Delta": "Delta",
    "Omicron_BA2": "Omicron BA.2",
}

VARIANT_ORDER = ["Alpha", "Beta", "Delta", "Omicron_BA2"]

# Threshold for high NSI.
# You can adjust this if needed.
HIGH_NSI_THRESHOLD = 0.50


# =========================================================
# Style
# =========================================================

plt.rcParams.update(
    {
        "font.family": "Arial",
        "font.size": 8,
        "axes.linewidth": 0.8,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
)

COLORS = {
    "yes": "#8B1E3F",       # deep reddish
    "partial": "#D98C8C",   # light rose
    "no": "#F4EAEA",        # pale rose
    "border": "#3A2A2A",
    "text": "#221A1A",
}


# =========================================================
# Load data
# =========================================================

if not INPUT_CSV.exists():
    raise FileNotFoundError(
        f"Input file was not found:\n{INPUT_CSV}\n\n"
        "Please run your Figure 4 NSI script first."
    )

df = pd.read_csv(INPUT_CSV)

required_cols = [
    "Group",
    "Variant",
    "Position",
    "Reference_AA",
    "Variant_consensus_AA",
    "Residue_change",
    "Smoothed_NSI",
    "Delta_NSI_vs_Wuhan",
]

missing = [c for c in required_cols if c not in df.columns]
if missing:
    raise ValueError(f"Missing required columns: {missing}")

df["Position"] = pd.to_numeric(df["Position"], errors="coerce")
df["Smoothed_NSI"] = pd.to_numeric(df["Smoothed_NSI"], errors="coerce")
df["Delta_NSI_vs_Wuhan"] = pd.to_numeric(df["Delta_NSI_vs_Wuhan"], errors="coerce")

df = df.dropna(subset=["Position"])
df["Position"] = df["Position"].astype(int)


# =========================================================
# Build residue overlap table
# =========================================================

rows = []

for pos in RESIDUE_ORDER:
    pos_df = df[df["Position"] == pos].copy()

    if pos_df.empty:
        continue

    wuhan_row = pos_df[pos_df["Group"] == "Wuhan"]

    if len(wuhan_row) > 0:
        ref_aa = str(wuhan_row.iloc[0]["Reference_AA"])
    else:
        ref_aa = str(pos_df.iloc[0]["Reference_AA"])

    # Determine residue label.
    # If mutations exist, show reference/mutant label.
    mutation_labels = []
    mutation_variants = []

    for group in VARIANT_ORDER:
        gdf = pos_df[pos_df["Group"] == group]

        if gdf.empty:
            continue

        row = gdf.iloc[0]
        ref = str(row["Reference_AA"])
        aa = str(row["Variant_consensus_AA"])

        if aa != ref and aa not in ["-", "X", "?", ".", "*"]:
            mutation_variants.append(VARIANT_DISPLAY.get(group, group))
            mutation_labels.append(f"{ref}{pos}{aa}")

    if mutation_labels:
        residue_label = f"{ref_aa}{pos}/" + "/".join(sorted(set([m[-1] + str(pos) for m in mutation_labels])))
    else:
        residue_label = f"{ref_aa}{pos}"

    # Interface status.
    if pos in ACE2_DIRECT_INTERFACE:
        interface_status = "Yes"
        interface_code = 1.0
    elif pos in ACE2_NEAR_INTERFACE:
        interface_status = "Near"
        interface_code = 0.5
    else:
        interface_status = "No"
        interface_code = 0.0

    # Mutation status.
    if mutation_variants:
        mutation_status = ", ".join(mutation_variants)
        mutation_code = 1.0
    else:
        mutation_status = "No"
        mutation_code = 0.0

    # High NSI status.
    nsi_values = pos_df["Smoothed_NSI"].dropna().astype(float)
    max_nsi = float(nsi_values.max()) if len(nsi_values) else np.nan

    high_nsi_groups = []
    for group in ["Wuhan", "Alpha", "Beta", "Delta", "Omicron_BA2"]:
        gdf = pos_df[pos_df["Group"] == group]

        if gdf.empty:
            continue

        nsi_value = float(gdf.iloc[0]["Smoothed_NSI"])

        if nsi_value >= HIGH_NSI_THRESHOLD:
            high_nsi_groups.append(VARIANT_DISPLAY.get(group, group))

    if high_nsi_groups:
        high_nsi_status = ", ".join(high_nsi_groups)
        high_nsi_code = 1.0
    else:
        high_nsi_status = "No"
        high_nsi_code = 0.0

    # Mean delta NSI among non-Wuhan variants.
    non_wuhan = pos_df[pos_df["Group"] != "Wuhan"]
    mean_delta = float(non_wuhan["Delta_NSI_vs_Wuhan"].mean()) if len(non_wuhan) else 0.0
    max_delta = float(non_wuhan["Delta_NSI_vs_Wuhan"].max()) if len(non_wuhan) else 0.0

    rows.append(
        {
            "Position": pos,
            "Residue": residue_label,
            "Interface": interface_status,
            "Mutation": mutation_status,
            "High_NSI": high_nsi_status,
            "Max_NSI": max_nsi,
            "Mean_delta_NSI_vs_Wuhan": mean_delta,
            "Max_delta_NSI_vs_Wuhan": max_delta,
            "Importance": IMPORTANCE.get(pos, ""),
            "Interface_code": interface_code,
            "Mutation_code": mutation_code,
            "High_NSI_code": high_nsi_code,
        }
    )

table_df = pd.DataFrame(rows)
table_df.to_csv(OUTPUT_TABLE, index=False)


# =========================================================
# Plot overlap map
# =========================================================

plot_cols = ["Interface_code", "Mutation_code", "High_NSI_code"]
plot_labels = ["ACE2\ninterface", "Variant\nmutation", "High\nNSI"]

matrix = table_df[plot_cols].values.astype(float)

fig, ax = plt.subplots(figsize=(6.2, 3.9), facecolor="white")

n_rows, n_cols = matrix.shape

# Draw cells manually for clean publication-style table.
for i in range(n_rows):
    for j in range(n_cols):
        value = matrix[i, j]

        if value >= 1.0:
            color = COLORS["yes"]
            text_color = "white"
            marker = "Yes"
        elif value > 0:
            color = COLORS["partial"]
            text_color = COLORS["text"]
            marker = "Near"
        else:
            color = COLORS["no"]
            text_color = COLORS["text"]
            marker = "No"

        ax.add_patch(
            Rectangle(
                (j, i),
                1,
                1,
                facecolor=color,
                edgecolor="white",
                linewidth=1.2,
            )
        )

        ax.text(
            j + 0.5,
            i + 0.5,
            marker,
            ha="center",
            va="center",
            fontsize=7.2,
            fontweight="bold",
            color=text_color,
        )

# Add residue labels.
ax.set_yticks(np.arange(n_rows) + 0.5)
ax.set_yticklabels(table_df["Residue"], fontsize=8.5, fontweight="bold")

ax.set_xticks(np.arange(n_cols) + 0.5)
ax.set_xticklabels(plot_labels, fontsize=8.2, fontweight="bold")

ax.set_xlim(0, n_cols)
ax.set_ylim(n_rows, 0)

# Right-side importance labels.
for i, row in table_df.iterrows():
    ax.text(
        n_cols + 0.18,
        i + 0.5,
        row["Importance"],
        ha="left",
        va="center",
        fontsize=7.2,
        color=COLORS["text"],
    )

ax.text(
    n_cols + 0.18,
    -0.25,
    "Functional interpretation",
    ha="left",
    va="bottom",
    fontsize=8.2,
    fontweight="bold",
    color=COLORS["text"],
)

# Box around heatmap.
for spine in ["top", "right", "left", "bottom"]:
    ax.spines[spine].set_visible(True)
    ax.spines[spine].set_linewidth(0.9)
    ax.spines[spine].set_color("black")

ax.tick_params(axis="both", length=0)
ax.set_title("Residue-level convergence at the RBD/RBM interface", fontsize=10, fontweight="bold", pad=10)

# Expand x limit to make room for interpretation text.
ax.set_xlim(0, n_cols + 3.2)

plt.tight_layout()

fig.savefig(OUTPUT_PNG, dpi=900, bbox_inches="tight", facecolor="white")
fig.savefig(OUTPUT_PDF, bbox_inches="tight", facecolor="white")
plt.close(fig)


print("\nSaved Figure 5D:")
print(f"  {OUTPUT_PNG}")
print(f"  {OUTPUT_PDF}")
print(f"  {OUTPUT_TABLE}")

print("\nResidue overlap table:")
print(
    table_df[
        [
            "Residue",
            "Interface",
            "Mutation",
            "High_NSI",
            "Max_NSI",
            "Mean_delta_NSI_vs_Wuhan",
            "Importance",
        ]
    ].to_string(index=False)
)