"""
Code developed by:
Nitish Katoch

Script title
------------
ML02: Extraction of nitrosative stress target residues from Wuhan-aligned spike sequences

Purpose
-------
This script extracts biologically relevant nitrosative stress target residues
(Cysteine and Tyrosine) from a Wuhan-coordinate multiple-sequence alignment.
It converts the aligned FASTA into a structured matrix suitable for downstream
machine learning, feature engineering, and NSI modelling.

This script is a data transformation and feature preparation step. It does not
perform machine learning, but it defines the residue-level dataset used by ML03
and beyond.

Scientific rationale
-------------------
Reactive nitrogen species (RNS) primarily modify:

    Cysteine (C) -> S-nitrosylation
    Tyrosine (Y) -> Tyrosine nitration

Therefore, positions containing C or Y in the Wuhan reference are treated as
biologically meaningful target sites.

Input
-----
Required aligned FASTA:

    02_CuratedRawData/combined_curated_wuhan_coordinate.fasta

This file must be generated by ML01 and must already be in Wuhan coordinate space.

Libraries used
--------------
pathlib
    Path handling.

collections
    Efficient storage of tabular data.

Bio.AlignIO
    Reads multiple sequence alignment.

numpy
    Numerical matrix construction for heatmaps.

matplotlib / seaborn
    Generation of publication-quality figures.

Calculations and processing
---------------------------
1. Load the multiple sequence alignment.
2. Use the first sequence (Wuhan reference) as coordinate template.
3. Identify all positions where the reference has:
        C or Y
4. For each such position:
        Extract the amino acid across all variants.
5. Build a matrix:

        Rows    = Variants
        Columns = Target residue positions

6. Encode residue state numerically:

        0 = Gap (-)
        1 = Cysteine (C)
        2 = Tyrosine (Y)
        3 = Mutation (any other amino acid)

7. Count per-variant abundance:

        Number of C residues
        Number of Y residues

8. Detect variable positions:

        Position is variable if more than one state exists across variants

Outputs
-------
1. extracted_nitro_targets.csv
   Matrix of Variant_ID × residue positions

2. residue_distribution_across_variants.png
   Bar plot showing number of C and Y residues per variant

3. cys_tyr_conservation_heatmap.png
   Heatmap showing conservation/mutation state at each target position

Plot descriptions
-----------------
Plot 1: Distribution plot
    X-axis: variants
    Y-axis: count of C and Y residues
    Purpose: compare nitrosative susceptibility potential across variants

Plot 2: Heatmap
    X-axis: residue positions (Wuhan coordinates)
    Y-axis: variants
    Values:
        0 gap
        1 cysteine
        2 tyrosine
        3 mutation
    Purpose: visualize conservation and mutation patterns

Pipeline position
-----------------
ML01 -> ML02 -> ML03 -> ML04 -> ML05
"""
from pathlib import Path
import collections
import matplotlib.pyplot as plt
import seaborn as sns
from Bio import AlignIO
import numpy as np

# ============================================================================= #
# 1. PATHS & CONFIGURATION
# ============================================================================= #
BASE_DIR = Path(__file__).resolve().parent

# Source path from your previous step's output curation folder
CURATED_DIR = BASE_DIR / "02_CuratedRawData"
INPUT_ALIGNED_FASTA = CURATED_DIR / "combined_curated_wuhan_coordinate.fasta"

# Dedicated output directory for our AI/ML framework pipeline
OUTPUT_DIR = BASE_DIR / "09_AI_NitroSpike"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Target output files
OUTPUT_CSV = OUTPUT_DIR / "extracted_nitro_targets.csv"
PLOT_DISTRIBUTION = OUTPUT_DIR / "residue_distribution_across_variants.png"
PLOT_CONSERVATION = OUTPUT_DIR / "cys_tyr_conservation_heatmap.png"

# ----------------------------------------------------------------------------- #
# --- USER VISUALIZATION CONTROL PANELS ---
# Adjust these explicit configuration tokens to change chart dimensions instantly
# ----------------------------------------------------------------------------- #
DISTRIBUTION_WIDTH = 25.0     # Increase to stretch the absolute count bars horizontally
DISTRIBUTION_HEIGHT = 6.0     # Vertical canvas size for the bar distribution layout

CONSERVATION_WIDTH_MULTIPLIER = 0.55  # Horizontal width scaling step per target column 
CONSERVATION_HEIGHT = 30    # Increase to give variant rows more breathing space vertically

# Target residues susceptible to RNS (Nitrosative stress) from plasma water:
# Cysteine (C) -> Subject to S-Nitrosylation
# Tyrosine (Y) -> Subject to Tyrosine Nitration
TARGET_AMINO_ACIDS = {"C", "Y"}


# ============================================================================= #
# 2. MAIN WORKFLOW
# ============================================================================= #
def main():
    print(f"[1/4] Loading multi-sequence alignment file...")
    if not INPUT_ALIGNED_FASTA.exists():
        raise FileNotFoundError(f"Prerequisite alignment asset missing: {INPUT_ALIGNED_FASTA}")
        
    # Load aligned spike protein sequences
    alignment = AlignIO.read(str(INPUT_ALIGNED_FASTA), "fasta")
    total_variants = len(alignment)
    alignment_length = alignment.get_alignment_length()
    print(f"  Successfully ingested {total_variants} variant tracks with alignment length {alignment_length}.")

    # --------------------------------------------------------------------------
    # STEP 1: LOCATE ALL POSITIONS WITH SUSCEPTIBLE AMINO ACIDS IN THE REFERENCE
    # The first sequence in our alignment serves as our spatial structural template (e.g., Wuhan)
    # --------------------------------------------------------------------------
    print(f"\n[2/4] Scanning reference template for RNS-vulnerable positions...")
    ref_record = alignment[0]
    target_positions = []  # List of tuples: (residue_type, 1_based_position_index)

    # Identify C and Y positions in Wuhan reference
    for idx in range(alignment_length):
        amino_acid = ref_record.seq[idx]
        if amino_acid in TARGET_AMINO_ACIDS:
            # Storing structural context (1-based mapping for real-world PDB correlation)
            target_positions.append((amino_acid, idx + 1))

    print(f"  Identified {len(target_positions)} total target sites in reference structure.")

    # --------------------------------------------------------------------------
    # STEP 2: CONSTRUCT TABULAR SUMMARY MATRIX FOR FEATURE PROCESSING
    # --------------------------------------------------------------------------
    csv_data = collections.defaultdict(list)
    
    # Trackers for drawing our descriptive statistics distribution plot
    variant_names = []
    cys_counts = []
    tyr_counts = []

    # Trackers to construct a structured numerical array for our horizontal layout
    # Matrix format: Rows = Variant Axis, Columns = Target Positions
    heatmap_data = []
    residue_names = [f"{res_type}{pos}" for res_type, pos in target_positions]
    mutated_positions = 0

    # Initialize variant names and rows for our tracking sheets
    for record in alignment:
        variant_names.append(record.id)
        csv_data["Variant_ID"].append(record.id)

    # Temporary structured array to gather columns first
    position_matrix_transpose = []

    # Build feature matrix across variants for each target position
    for res_type, pos_1based in target_positions:
        idx_0based = pos_1based - 1
        column_key = f"{res_type}{pos_1based}"
        
        # Array to hold numeric categories for this single sequence coordinate
        # 0: Absent/Gap, 1: Cysteine (C), 2: Tyrosine (Y), 3: Mutated State (Other)
        position_states_column = []
        
        for record in alignment:
            observed_aa = record.seq[idx_0based]
            csv_data[column_key].append(observed_aa)
            
            if observed_aa == "-":
                position_states_column.append(0)
            elif observed_aa == "C":
                position_states_column.append(1)
            elif observed_aa == "Y":
                position_states_column.append(2)
            else:
                position_states_column.append(3) # Evolutionary mutation swap

        position_matrix_transpose.append(position_states_column)
        
        # Trace if the target position underwent any mutation away from the base template state
        if len(set(position_states_column)) > 1:
            mutated_positions += 1

    # Transpose the tracking matrix so rows map to variants and columns map to residues
    # Convert to matrix format for visualization
    heatmap_matrix = np.array(position_matrix_transpose).T  # Shape: (Num_Variants, Num_Residues)

    # Populate the distribution counting channels per variant for Plot 1
    for record in alignment:
        c_count = sum(1 for (res, pos) in target_positions if record.seq[pos-1] == "C")
        y_count = sum(1 for (res, pos) in target_positions if record.seq[pos-1] == "Y")
        cys_counts.append(c_count)
        tyr_counts.append(y_count)

    # Save target matrix down to disk
    df_out = pd.DataFrame(csv_data) if 'pd' in globals() else None
    if df_out is None:
        import pandas as pd
        df_out = pd.DataFrame(csv_data)
        
    df_out.to_csv(OUTPUT_CSV, index=False)
    print(f"  Target isolation matrix successfully saved -> {OUTPUT_CSV}")

    # ============================================================================= #
    # 3. GRAPHICAL PLOTTING ENGINES
    # ============================================================================= #
    print(f"\n[3/4] Exporting publication-quality diagnostic framework charts...")
    sns.set_theme(style="whitegrid")

    # --- PLOT 1: BIOPHYSICAL DISTRIBUTIONS ---
    # Controlled dynamically via explicit tokens declared at setup header
    # Plot 1: distribution of target residues
    plt.figure(figsize=(DISTRIBUTION_WIDTH, DISTRIBUTION_HEIGHT))
    x_indices = np.arange(len(variant_names))
    bar_width = 0.35

    plt.bar(x_indices - bar_width/2, cys_counts, bar_width, label='Cysteines (S-Nitrosylation)', color='#1f77b4', edgecolor='black', alpha=0.9)
    plt.bar(x_indices + bar_width/2, tyr_counts, bar_width, label='Tyrosines (Nitration)', color='#ff7f0e', edgecolor='black', alpha=0.9)

    plt.title("Preserved Target Amino Acid Abundance Profiles Across Strains", fontsize=12, fontweight='bold', pad=15)
    plt.xlabel("SARS-CoV-2 Tracked Variant Lineage", fontsize=11, labelpad=10)
    plt.ylabel("Absolute Amino Acid Coordinate Count", fontsize=11)
    plt.xticks(x_indices, variant_names, rotation=30, ha='right', fontsize=10)
    plt.legend(loc="upper right", frameon=True) 
    plt.tight_layout()
    plt.savefig(PLOT_DISTRIBUTION, dpi=300)
    plt.close()
    print(f"  Saved distribution profile chart [Width={DISTRIBUTION_WIDTH}] to: {PLOT_DISTRIBUTION}")

    # --- PLOT 2: HORIZONTAL MATRIX CONSERVATION HEATMAP ---
    # Controlled dynamically via explicit tokens declared at setup header
    fig_width = max(14, len(residue_names) * CONSERVATION_WIDTH_MULTIPLIER)
    # Plot 1: distribution of target residues
    plt.figure(figsize=(fig_width, CONSERVATION_HEIGHT))

    # Heatmap color rendering
    # Plot 2: conservation heatmap
    sns.heatmap(
        heatmap_matrix, 
        annot=True, 
        fmt="d", 
        cmap="YlGnBu", 
        xticklabels=residue_names,  # Target positions stretch across the X-axis
        yticklabels=variant_names,  # Strains track vertically down the Y-axis
        cbar_kws={
            'label': 'State Index (0: Gap, 1: Cys, 2: Tyr, 3: Mutation Breakpoint)',
            'ticks': [0, 1, 2, 3],
            'orientation': 'horizontal',
            'pad': 0.10                 
        },
        linewidths=0.6,
        linecolor="#e0e0e0"
    )

    plt.title(
        f"Target Site Conservation Matrix Across Extracted Sequence Variants\n"
        f"(Detected {mutated_positions} hyper-variable positions out of {len(residue_names)} total)", 
        fontsize=12, 
        fontweight='bold', 
        pad=20
    )
    plt.xlabel("Target Residue Coordinate Label (Type + Reference Position)", fontsize=11, labelpad=12)
    plt.ylabel("SARS-CoV-2 Variant Lineage", fontsize=11, labelpad=12)
    plt.xticks(rotation=90, fontsize=9)  # Stack residue text vertically for clean horizontal packing
    plt.yticks(rotation=0, fontsize=10)  # Keep strain text perfectly readable

    plt.tight_layout()
    plt.savefig(PLOT_CONSERVATION, dpi=500)
    plt.close()
    print(f"  Saved horizontal conservation heatmap [Height={CONSERVATION_HEIGHT}] to: {PLOT_CONSERVATION}")
    print(f"\n[4/4] SEQUENCE FILTERING PHASE EXECUTED SUCCESSFULLY.\n")

if __name__ == "__main__":
    main()