"""
Code developed by:
Nitish Katoch

Script title
------------
ML04: Hierarchical Nitrosative Susceptibility Index (NSI) generation and sensitivity analysis

Purpose
-------
This script is the core methodological component of the NitroSpike framework.
It computes a biologically grounded Nitrosative Susceptibility Index (NSI)
using a hierarchical multi-component model instead of a single weighted feature sum.

This script also performs:
    - Residue-level ranking
    - Variant-level ranking
    - Feature ablation analysis
    - Tree-based sensitivity analysis
    - Optional supervised classification (if independent labels are present)

Scientific concept
------------------
NSI is a proxy susceptibility score derived from four biological dimensions:

    1. Accessibility
    2. Chemical microenvironment
    3. Evolutionary context
    4. Functional context

Each component is constructed from normalized structural and sequence features.

Important:
    NSI is NOT a ground-truth label.
    It is a mechanistic prioritization score.

Input
-----
09_AI_NitroSpike/structural_ai_feature_matrix.csv

Generated from ML03.

Key calculations
----------------
Accessibility component:
    Mean of normalized:
        - Relative SASA
        - Exposure proxy
        - Residue depth

Chemistry component:
    Mean of:
        - Electrostatic balance
        - Hydrophobic/polar/aromatic/sulfur composition
        - Disulfide penalty (for cysteine)

Evolution component:
    Mean of:
        - Conservation frequency
        - Shannon entropy

Functional context:
    Mean of:
        - Distance to ACE2 interface (inverted)
        - Distance to glycan shielding
        - RBD / RBM location indicators

Final NSI:
    NSI = 0.35*Accessibility
        + 0.30*Chemistry
        + 0.20*Evolution
        + 0.15*Functional

Machine learning components
---------------------------
1. Tree-based regression (default mode)
    - Target: NSI proxy score
    - Purpose: feature sensitivity analysis

2. Supervised classification (optional)
    - Runs only if independent label column exists
    - Uses:
        Random Forest OR XGBoost
    - Validation:
        Group-aware split (Variant_ID)
        GroupKFold cross-validation

3. Feature importance:
    - Permutation importance
    - Nonlinear sensitivity assessment

Validation strategy
-------------------
- GroupShuffleSplit (variant-level separation)
- GroupKFold cross-validation
- Avoids leakage across variants
- Regression evaluated using R²
- Classification evaluated using:
        ROC-AUC
        Precision-Recall
        Confusion matrix

Ablation analysis
-----------------
Each NSI component is removed one at a time:

    - Recompute NSI
    - Compare ranking vs baseline
    - Compute:
        Spearman rank correlation
        Mean rank shift

Outputs
-------
- nsi_ranked_candidate_sites.csv
- nsi_residue_level_ranking.csv
- nsi_component_scores.csv
- nsi_ablation_summary.csv
- tree_feature_importance.csv
- tree_model_evaluation_report.txt

Plots:
- NSI distribution
- Top variant-level sites
- Top residue-level sites
- Component contribution
- Ablation stability
- Feature importance
- ROC / PR curves (if classification)

Pipeline position
-----------------
ML01 -> ML02 -> ML03 -> ML04 -> ML05

Publication note
----------------
NSI is a hypothesis-generating prioritization metric.
Tree-based models are used for sensitivity analysis, not primary prediction.
"""

"""
103_generate_nsi_ranking_and_tree_sensitivity_updated.py

Purpose
-------
Generate a reviewer-safe Nitrosative Susceptibility Index (NSI) from the
feature matrix produced by script 102, using a hierarchical biological scoring
scheme rather than a single feature-dominated weighted sum.

Main design
-----------
1. No synthetic binary labels are generated.
2. NSI is computed from four biological components:
   - Accessibility
   - Chemical microenvironment
   - Evolutionary context
   - Functional context
3. Each component is built from normalized subfeatures.
4. Residue-level rankings are generated by aggregating Variant x Residue scores.
5. Feature-family ablation and tree-based sensitivity analysis are exported.
6. Supervised classification is run only if an independent curated binary label
   column is present.

Expected input
--------------
09_AI_NitroSpike/structural_ai_feature_matrix.csv
or
09_AI_NitroSpike/engineered_structural_features.csv

Main outputs
------------
09_AI_NitroSpike/nsi_ranked_candidate_sites.csv
09_AI_NitroSpike/nsi_residue_level_ranking.csv
09_AI_NitroSpike/nsi_component_scores.csv
09_AI_NitroSpike/nsi_ablation_summary.csv
09_AI_NitroSpike/tree_feature_importance.csv
09_AI_NitroSpike/tree_model_evaluation_report.txt

Interpretation
--------------
NSI is a transparent prioritization score. It is not an experimental ground
truth label. Classification metrics are meaningful only when a curated or
experimental label column is provided.
"""

from pathlib import Path
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.inspection import permutation_importance
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
    average_precision_score,
    r2_score,
)
from sklearn.model_selection import GroupKFold, GroupShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

try:
    import xgboost as xgb
    XGBOOST_AVAILABLE = True
except ImportError:
    XGBOOST_AVAILABLE = False

warnings.filterwarnings("ignore", category=UserWarning)

# =============================================================================
# 1. PATHS AND CONFIGURATION
# =============================================================================
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "09_AI_NitroSpike"

INPUT_CANDIDATES = [
    DATA_DIR / "structural_ai_feature_matrix.csv",
    DATA_DIR / "engineered_structural_features.csv",
]

OUTPUT_RANKED_NSI = DATA_DIR / "nsi_ranked_candidate_sites.csv"
OUTPUT_RESIDUE_RANKING = DATA_DIR / "nsi_residue_level_ranking.csv"
OUTPUT_COMPONENTS = DATA_DIR / "nsi_component_scores.csv"
OUTPUT_ABLATION = DATA_DIR / "nsi_ablation_summary.csv"
OUTPUT_MODEL_REPORT = DATA_DIR / "tree_model_evaluation_report.txt"
OUTPUT_FEATURE_IMPORTANCE = DATA_DIR / "tree_feature_importance.csv"

PLOT_NSI_DISTRIBUTION = DATA_DIR / "nsi_score_distribution.png"
PLOT_TOP_VARIANT_SITES = DATA_DIR / "top_nsi_candidate_sites_variant_level.png"
PLOT_TOP_RESIDUES = DATA_DIR / "top_nsi_candidate_sites_residue_level.png"
PLOT_COMPONENT_IMPORTANCE = DATA_DIR / "nsi_component_contribution_summary.png"
PLOT_ABLATION = DATA_DIR / "nsi_ablation_rank_stability.png"
PLOT_FEATURE_IMPORTANCE = DATA_DIR / "tree_feature_importance.png"
PLOT_CONFUSION_MATRIX = DATA_DIR / "classification_confusion_matrix.png"
PLOT_ROC = DATA_DIR / "classification_roc_curve.png"
PLOT_PR = DATA_DIR / "classification_precision_recall_curve.png"

RANDOM_STATE = 42
TEST_SIZE = 0.25
N_SPLITS = 4
TOP_N_PLOT = 30

LABEL_CANDIDATES = [
    "Experimental_Label",
    "Curated_Susceptibility_Label",
    "Susceptibility_Label",
]

# Hierarchical component weights. These are explicit assumptions and should be
# reported as part of the proxy NSI model.
COMPONENT_WEIGHTS = {
    "Accessibility_Component": 0.35,
    "Chemistry_Component": 0.30,
    "Evolution_Component": 0.20,
    "Functional_Context_Component": 0.15,
}

# Metadata and QC columns are retained in output but excluded from ML.
EXCLUDE_FROM_MODEL = {
    "Variant_ID",
    "PDB_Template",
    "Chain_ID",
    "Model_ID",
    "Residue_Label",
    "Residue_Found",
    "Structure_Coverage_Status",
    "Missing_In_PDB",
    "Reference_AA",
    "Observed_AA",
    "Target_Status",
    "NSI_Proxy_Score",
    "NSI_Rank",
    "Experimental_Label",
    "Curated_Susceptibility_Label",
    "Susceptibility_Label",
}

PRIMARY_MODEL_FEATURES = [
    "Residue_Type",
    "Domain",
    "Relative_SASA",
    "Packing_Density_Exposure_Proxy",
    "Electrostatic_Balance_8A",
    "Hydrophobic_Count_8A",
    "Polar_Count_8A",
    "Aromatic_Count_8A",
    "Sulfur_Count_8A",
    "Residue_Depth_Proxy_A",
    "Nearest_ACE2_Interface_Distance_A",
    "Nearest_Glycan_Sequon_Distance_A",
    "Conservation_Frequency",
    "Shannon_Entropy",
    "Disulfide_Bonded",
]

# =============================================================================
# 2. UTILITY FUNCTIONS
# =============================================================================
def find_input_file() -> Path:
    for path in INPUT_CANDIDATES:
        if path.exists():
            return path
    raise FileNotFoundError(
        "No feature matrix found. Expected one of:\n" +
        "\n".join(str(path) for path in INPUT_CANDIDATES)
    )


def first_existing(df: pd.DataFrame, names: list[str]) -> str | None:
    for name in names:
        if name in df.columns:
            return name
    return None


def numeric_series(df: pd.DataFrame, name: str | None, default: float = 0.0) -> pd.Series:
    if name is None or name not in df.columns:
        return pd.Series(default, index=df.index, dtype=float)
    return pd.to_numeric(df[name], errors="coerce").astype(float)


def minmax(series: pd.Series, invert: bool = False, fill_value: float | None = None) -> pd.Series:
    x = pd.to_numeric(series, errors="coerce").astype(float)
    if x.notna().sum() == 0:
        scaled = pd.Series(np.zeros(len(x)), index=x.index, dtype=float)
    else:
        if fill_value is None:
            x = x.fillna(x.median())
        else:
            x = x.fillna(fill_value)
        xmin, xmax = x.min(), x.max()
        if np.isclose(xmax, xmin):
            scaled = pd.Series(np.zeros(len(x)), index=x.index, dtype=float)
        else:
            scaled = (x - xmin) / (xmax - xmin)
    return 1.0 - scaled if invert else scaled


def safe_mean(columns: list[pd.Series], index: pd.Index) -> pd.Series:
    valid = [col for col in columns if col is not None]
    if not valid:
        return pd.Series(0.0, index=index, dtype=float)
    mat = pd.concat(valid, axis=1)
    return mat.mean(axis=1).fillna(0.0)


def choose_label_column(df: pd.DataFrame) -> str | None:
    for col in LABEL_CANDIDATES:
        if col in df.columns:
            values = set(pd.Series(df[col]).dropna().unique())
            if values.issubset({0, 1, 0.0, 1.0, True, False}):
                return col
    return None


def get_groups(df: pd.DataFrame) -> np.ndarray:
    if "Variant_ID" in df.columns:
        return df["Variant_ID"].astype(str).values
    if "PDB_Template" in df.columns:
        return df["PDB_Template"].astype(str).values
    return np.arange(len(df))


def residue_label_from_row(row: pd.Series) -> str:
    if "Residue_Label" in row and pd.notna(row["Residue_Label"]):
        return str(row["Residue_Label"])
    if "Reference_AA" in row and "Sequence_Position" in row:
        return f"{row['Reference_AA']}{int(row['Sequence_Position'])}"
    if "Sequence_Position" in row:
        return str(int(row["Sequence_Position"]))
    return str(row.name)


# =============================================================================
# 3. HIERARCHICAL NSI SCORING
# =============================================================================
# Core NSI calculation using hierarchical biological model

def compute_hierarchical_nsi(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    # -------------------------------------------------------------------------
    # Accessibility component
    # -------------------------------------------------------------------------
    relative_sasa_col = first_existing(out, ["Relative_SASA"])
    true_sasa_col = first_existing(out, ["True_SASA_A2", "True_SASA"])
    exposure_proxy_col = first_existing(out, ["Packing_Density_Exposure_Proxy", "Solvent_Exposure_Proxy"])
    residue_depth_col = first_existing(out, ["Residue_Depth_Proxy_A"])

    sasa_score = None
    if relative_sasa_col:
        sasa_score = minmax(out[relative_sasa_col])
    elif true_sasa_col:
        sasa_score = minmax(out[true_sasa_col])

    exposure_proxy_score = minmax(out[exposure_proxy_col]) if exposure_proxy_col else None
    depth_score = minmax(out[residue_depth_col]) if residue_depth_col else None

    # Accessibility score from exposure and structure
    out["Accessibility_Component"] = safe_mean(
        [sasa_score, exposure_proxy_score, depth_score],
        index=out.index,
    )

    # -------------------------------------------------------------------------
    # Chemistry component
    # -------------------------------------------------------------------------
    elec_col = first_existing(out, ["Electrostatic_Balance_8A", "Weighted_Electrostatic_Potential"])
    elec = numeric_series(out, elec_col, default=0.0).fillna(0.0)
    residue_type = out.get("Residue_Type", pd.Series("", index=out.index)).astype(str).str.lower()
    observed_aa = out.get("Observed_AA", pd.Series("", index=out.index)).astype(str)
    cys_mask = residue_type.str.contains("cys") | observed_aa.eq("C")
    elec_for_cys = minmax(elec)
    elec_for_tyr = minmax(elec.abs())
    electrostatic_score = pd.Series(np.where(cys_mask, elec_for_cys, elec_for_tyr), index=out.index)

    hydrophobic_score = minmax(numeric_series(out, first_existing(out, ["Hydrophobic_Count_8A"])))
    polar_score = minmax(numeric_series(out, first_existing(out, ["Polar_Count_8A"])))
    aromatic_score = minmax(numeric_series(out, first_existing(out, ["Aromatic_Count_8A"])))
    sulfur_score = minmax(numeric_series(out, first_existing(out, ["Sulfur_Count_8A"])))

    if "Disulfide_Bonded" in out.columns:
        disulfide = numeric_series(out, "Disulfide_Bonded", default=0.0).fillna(0.0).clip(0, 1)
        free_cys_score = 1.0 - disulfide
        non_cys_score = pd.Series(1.0, index=out.index)
        disulfide_adjusted_score = pd.Series(np.where(cys_mask, free_cys_score, non_cys_score), index=out.index)
    else:
        disulfide_adjusted_score = pd.Series(1.0, index=out.index)

    # Chemical environment contribution
    out["Chemistry_Component"] = safe_mean(
        [
            electrostatic_score,
            hydrophobic_score,
            polar_score,
            aromatic_score,
            sulfur_score,
            disulfide_adjusted_score,
        ],
        index=out.index,
    )

    # -------------------------------------------------------------------------
    # Evolution component
    # -------------------------------------------------------------------------
    conservation_col = first_existing(out, ["Conservation_Frequency", "Target_Retention_Frequency"])
    entropy_col = first_existing(out, ["Shannon_Entropy"])

    conservation_score = minmax(numeric_series(out, conservation_col)) if conservation_col else None
    entropy_score = minmax(numeric_series(out, entropy_col)) if entropy_col else None

    # Conserved residues support functional relevance; entropy supports variant-specific vulnerability.
    # Evolutionary conservation and variability
    out["Evolution_Component"] = safe_mean(
        [conservation_score, entropy_score],
        index=out.index,
    )

    # -------------------------------------------------------------------------
    # Functional context component
    # -------------------------------------------------------------------------
    ace2_col = first_existing(out, ["Nearest_ACE2_Interface_Distance_A", "Nearest_ACE2_Interface_Distance", "Interface_Proximity_Index"])
    glycan_col = first_existing(out, ["Nearest_Glycan_Sequon_Distance_A", "Nearest_Glycan_Distance"])

    if ace2_col is None:
        ace2_score = None
    elif ace2_col == "Interface_Proximity_Index":
        ace2_score = minmax(out[ace2_col])
    else:
        ace2_score = minmax(out[ace2_col], invert=True)

    # A higher distance from glycan sequons is interpreted as lower shielding.
    glycan_score = minmax(out[glycan_col]) if glycan_col else None

    if "Is_RBM" in out.columns:
        rbm_score = numeric_series(out, "Is_RBM", default=0.0).fillna(0.0).clip(0, 1)
    elif "Domain" in out.columns:
        rbm_score = out["Domain"].astype(str).str.contains("RBM", case=False, na=False).astype(float)
    else:
        rbm_score = None

    if "Is_RBD" in out.columns:
        rbd_score = 0.5 * numeric_series(out, "Is_RBD", default=0.0).fillna(0.0).clip(0, 1)
    elif "Domain" in out.columns:
        rbd_score = 0.5 * out["Domain"].astype(str).str.contains("RBD|RBM", case=False, regex=True, na=False).astype(float)
    else:
        rbd_score = None

    # Functional relevance (ACE2, glycan, domain)
    out["Functional_Context_Component"] = safe_mean(
        [ace2_score, glycan_score, rbm_score, rbd_score],
        index=out.index,
    )

    # -------------------------------------------------------------------------
    # Final NSI score
    # -------------------------------------------------------------------------
    # Final weighted NSI score
    out["NSI_Proxy_Score"] = sum(
        COMPONENT_WEIGHTS[component] * out[component]
        for component in COMPONENT_WEIGHTS
    )

    out["NSI_Rank"] = out["NSI_Proxy_Score"].rank(ascending=False, method="dense").astype(int)

    # Keep a compact component score output table.
    component_cols = [
        "Variant_ID", "Residue_Label", "Reference_AA", "Observed_AA", "Residue_Type",
        "Sequence_Position", "Domain", "NSI_Proxy_Score", "NSI_Rank",
        "Accessibility_Component", "Chemistry_Component", "Evolution_Component", "Functional_Context_Component",
    ]
    available_component_cols = [col for col in component_cols if col in out.columns]
    out[available_component_cols].to_csv(OUTPUT_COMPONENTS, index=False)

    return out


# =============================================================================
# 4. RESIDUE-LEVEL RANKING AND ABLATION
# =============================================================================
def save_nsi_outputs(df: pd.DataFrame) -> pd.DataFrame:
    ranked = df.sort_values("NSI_Proxy_Score", ascending=False).copy()
    ranked.to_csv(OUTPUT_RANKED_NSI, index=False)

    # Variant-level top candidates.
    top_variant = ranked.head(TOP_N_PLOT).copy()
    if "Residue_Label" in top_variant.columns and "Variant_ID" in top_variant.columns:
        labels = top_variant["Variant_ID"].astype(str) + " | " + top_variant["Residue_Label"].astype(str)
    elif "Sequence_Position" in top_variant.columns and "Variant_ID" in top_variant.columns:
        labels = top_variant["Variant_ID"].astype(str) + " | " + top_variant["Sequence_Position"].astype(str)
    else:
        labels = top_variant.index.astype(str)

    plt.figure(figsize=(9, max(5, len(top_variant) * 0.28)))
    plt.barh(labels[::-1], top_variant["NSI_Proxy_Score"].values[::-1], edgecolor="black")
    plt.xlabel("Proxy NSI score")
    plt.ylabel("Candidate site")
    plt.title(f"Top {len(top_variant)} Variant-Level Candidate Sites")
    plt.tight_layout()
    plt.savefig(PLOT_TOP_VARIANT_SITES, dpi=300)
    plt.close()

    # Score distribution.
    plt.figure(figsize=(7, 4.5))
    plt.hist(ranked["NSI_Proxy_Score"], bins=30, edgecolor="black")
    p95 = ranked["NSI_Proxy_Score"].quantile(0.95)
    median = ranked["NSI_Proxy_Score"].median()
    plt.axvline(median, linestyle="--", linewidth=1.5, label=f"Median = {median:.3f}")
    plt.axvline(p95, linestyle=":", linewidth=2.0, label=f"95th percentile = {p95:.3f}")
    plt.xlabel("Proxy Nitrosative Susceptibility Index")
    plt.ylabel("Candidate site count")
    plt.title("Distribution of Hierarchical Proxy NSI Scores")
    plt.legend()
    plt.tight_layout()
    plt.savefig(PLOT_NSI_DISTRIBUTION, dpi=300)
    plt.close()

    # Residue-level aggregation avoids repeated Variant x Residue entries.
    if "Residue_Label" not in ranked.columns:
        ranked["Residue_Label"] = ranked.apply(residue_label_from_row, axis=1)

    aggregation = {
        "NSI_Proxy_Score": ["mean", "max", "std", "count"],
        "Accessibility_Component": "mean",
        "Chemistry_Component": "mean",
        "Evolution_Component": "mean",
        "Functional_Context_Component": "mean",
    }
    optional_first = ["Reference_AA", "Residue_Type", "Sequence_Position", "Domain"]
    for col in optional_first:
        if col in ranked.columns:
            aggregation[col] = "first"
    if "Conservation_Frequency" in ranked.columns:
        aggregation["Conservation_Frequency"] = "mean"
    if "Shannon_Entropy" in ranked.columns:
        aggregation["Shannon_Entropy"] = "mean"

    residue_ranked = ranked.groupby("Residue_Label", dropna=False).agg(aggregation)
    residue_ranked.columns = ["_".join(col).strip("_") if isinstance(col, tuple) else col for col in residue_ranked.columns]
    residue_ranked = residue_ranked.rename(columns={
        "NSI_Proxy_Score_mean": "Mean_NSI",
        "NSI_Proxy_Score_max": "Max_NSI",
        "NSI_Proxy_Score_std": "SD_NSI",
        "NSI_Proxy_Score_count": "Variant_Record_Count",
    })
    residue_ranked = residue_ranked.reset_index()
    residue_ranked["Residue_Level_Rank"] = residue_ranked["Mean_NSI"].rank(ascending=False, method="dense").astype(int)
    residue_ranked = residue_ranked.sort_values(["Mean_NSI", "Max_NSI"], ascending=False)
    residue_ranked.to_csv(OUTPUT_RESIDUE_RANKING, index=False)

    top_residue = residue_ranked.head(TOP_N_PLOT).copy()
    plt.figure(figsize=(8.5, max(5, len(top_residue) * 0.30)))
    plt.barh(top_residue["Residue_Label"].iloc[::-1], top_residue["Mean_NSI"].iloc[::-1], edgecolor="black")
    plt.xlabel("Mean proxy NSI across variants")
    plt.ylabel("Wuhan-coordinate residue")
    plt.title(f"Top {len(top_residue)} Residue-Level Candidate Sites")
    plt.tight_layout()
    plt.savefig(PLOT_TOP_RESIDUES, dpi=300)
    plt.close()

    # Component contribution summary.
    component_means = ranked[list(COMPONENT_WEIGHTS.keys())].mean().sort_values(ascending=True)
    plt.figure(figsize=(7, 4.5))
    plt.barh(component_means.index, component_means.values, edgecolor="black")
    plt.xlabel("Mean component score")
    plt.title("Mean NSI Component Contributions")
    plt.tight_layout()
    plt.savefig(PLOT_COMPONENT_IMPORTANCE, dpi=300)
    plt.close()

    return residue_ranked


# Evaluate importance of each NSI component

def run_ablation_analysis(df: pd.DataFrame) -> pd.DataFrame:
    baseline = df.copy()
    if "Residue_Label" not in baseline.columns:
        baseline["Residue_Label"] = baseline.apply(residue_label_from_row, axis=1)

    baseline_residue = baseline.groupby("Residue_Label")["NSI_Proxy_Score"].mean().sort_values(ascending=False)
    baseline_rank = baseline_residue.rank(ascending=False, method="dense")

    records = []
    for removed_component in COMPONENT_WEIGHTS:
        remaining = [comp for comp in COMPONENT_WEIGHTS if comp != removed_component]
        remaining_weight_sum = sum(COMPONENT_WEIGHTS[comp] for comp in remaining)
        ablated_score = sum(
            (COMPONENT_WEIGHTS[comp] / remaining_weight_sum) * baseline[comp]
            for comp in remaining
        )
        temp = baseline[["Residue_Label"]].copy()
        temp["Ablated_NSI"] = ablated_score
        ablated_residue = temp.groupby("Residue_Label")["Ablated_NSI"].mean().sort_values(ascending=False)
        ablated_rank = ablated_residue.rank(ascending=False, method="dense")

        common = baseline_rank.index.intersection(ablated_rank.index)
        corr = baseline_rank.loc[common].corr(ablated_rank.loc[common], method="spearman") if len(common) > 1 else np.nan
        mean_abs_shift = (baseline_rank.loc[common] - ablated_rank.loc[common]).abs().mean() if len(common) else np.nan

        records.append({
            "Removed_Component": removed_component,
            "Spearman_Rank_Correlation_vs_Baseline": corr,
            "Mean_Absolute_Rank_Shift": mean_abs_shift,
            "Interpretation": "Lower correlation or higher rank shift means this component strongly influences ranking.",
        })

    ablation_df = pd.DataFrame(records).sort_values("Spearman_Rank_Correlation_vs_Baseline")
    ablation_df.to_csv(OUTPUT_ABLATION, index=False)

    plot_df = ablation_df.sort_values("Mean_Absolute_Rank_Shift", ascending=True)
    plt.figure(figsize=(8, 4.5))
    plt.barh(plot_df["Removed_Component"], plot_df["Mean_Absolute_Rank_Shift"], edgecolor="black")
    plt.xlabel("Mean absolute residue-rank shift after removal")
    plt.title("NSI Feature-Family Ablation Stability")
    plt.tight_layout()
    plt.savefig(PLOT_ABLATION, dpi=300)
    plt.close()

    return ablation_df


# =============================================================================
# 5. TREE-BASED SENSITIVITY AND OPTIONAL CLASSIFICATION
# =============================================================================
def build_feature_table(df: pd.DataFrame, label_col: str | None = None):
    available_primary = [col for col in PRIMARY_MODEL_FEATURES if col in df.columns]
    additional_components = [col for col in COMPONENT_WEIGHTS if col in df.columns]
    feature_cols = available_primary + [col for col in additional_components if col not in available_primary]

    additional_numeric = [
        col for col in df.columns
        if col not in EXCLUDE_FROM_MODEL
        and not col.startswith("_")
        and col not in feature_cols
        and pd.api.types.is_numeric_dtype(df[col])
    ]
    feature_cols.extend(additional_numeric)

    if label_col and label_col in feature_cols:
        feature_cols.remove(label_col)

    if not feature_cols:
        raise ValueError("No usable predictive features were found.")

    X = df[feature_cols].copy()
    numeric_cols = [col for col in feature_cols if pd.api.types.is_numeric_dtype(X[col])]
    categorical_cols = [col for col in feature_cols if col not in numeric_cols]
    return X, feature_cols, numeric_cols, categorical_cols


def make_preprocessor(numeric_cols: list[str], categorical_cols: list[str]) -> ColumnTransformer:
    transformers = []
    if numeric_cols:
        transformers.append((
            "numeric",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]),
            numeric_cols,
        ))
    if categorical_cols:
        transformers.append((
            "categorical",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore")),
            ]),
            categorical_cols,
        ))
    return ColumnTransformer(transformers=transformers, remainder="drop")


def make_classifier():
    if XGBOOST_AVAILABLE:
        return xgb.XGBClassifier(
            n_estimators=250,
            max_depth=3,
            learning_rate=0.03,
            subsample=0.85,
            colsample_bytree=0.85,
            min_child_weight=2,
            reg_lambda=2.0,
            objective="binary:logistic",
            eval_metric="logloss",
            random_state=RANDOM_STATE,
        )
    return RandomForestClassifier(
        n_estimators=500,
        max_depth=5,
        min_samples_leaf=3,
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )


def make_regressor():
    return RandomForestRegressor(
        n_estimators=500,
        max_depth=5,
        min_samples_leaf=3,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )


def save_permutation_importance(model, X_test, y_test, feature_cols, scoring: str) -> pd.DataFrame:
    perm = permutation_importance(
        model,
        X_test,
        y_test,
        n_repeats=30,
        random_state=RANDOM_STATE,
        scoring=scoring,
    )
    importance_df = pd.DataFrame({
        "Feature": feature_cols,
        "Permutation_Importance_Mean": perm.importances_mean,
        "Permutation_Importance_SD": perm.importances_std,
    }).sort_values("Permutation_Importance_Mean", ascending=False)
    importance_df.to_csv(OUTPUT_FEATURE_IMPORTANCE, index=False)

    top_imp = importance_df.head(25).iloc[::-1]
    plt.figure(figsize=(8, max(4, len(top_imp) * 0.32)))
    plt.barh(top_imp["Feature"], top_imp["Permutation_Importance_Mean"], edgecolor="black")
    plt.xlabel(f"Permutation importance ({scoring})")
    plt.title("Tree-Based Feature Sensitivity")
    plt.tight_layout()
    plt.savefig(PLOT_FEATURE_IMPORTANCE, dpi=300)
    plt.close()
    return importance_df


# Tree-based regression to assess feature sensitivity

def run_nsi_regression(df: pd.DataFrame) -> str:
    X, feature_cols, numeric_cols, categorical_cols = build_feature_table(df)
    y = pd.to_numeric(df["NSI_Proxy_Score"], errors="coerce").values
    groups = get_groups(df)

    valid = np.isfinite(y)
    X = X.loc[valid].copy()
    y = y[valid]
    groups = groups[valid]

    model = Pipeline([
        ("preprocess", make_preprocessor(numeric_cols, categorical_cols)),
        ("model", make_regressor()),
    ])

    unique_groups = np.unique(groups)
    if len(unique_groups) >= 3:
        splitter = GroupShuffleSplit(n_splits=1, test_size=TEST_SIZE, random_state=RANDOM_STATE)
        train_idx, test_idx = next(splitter.split(X, y, groups=groups))
    else:
        rng = np.random.default_rng(RANDOM_STATE)
        indices = np.arange(len(X))
        rng.shuffle(indices)
        cut = int(len(indices) * (1.0 - TEST_SIZE))
        train_idx, test_idx = indices[:cut], indices[cut:]

    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    test_r2 = r2_score(y_test, y_pred) if len(X_test) > 1 else np.nan
    save_permutation_importance(model, X_test, y_test, feature_cols, scoring="r2")

    report = []
    report.append("NITROSATIVE SUSCEPTIBILITY INDEX REPORT")
    report.append("=" * 60)
    report.append("Mode: hierarchical proxy NSI ranking and tree-based sensitivity")
    report.append("")
    report.append("NSI model:")
    for component, weight in COMPONENT_WEIGHTS.items():
        report.append(f"  {component}: {weight:.2f}")
    report.append("")
    report.append("Interpretation:")
    report.append("The NSI_Proxy_Score is a transparent residue-prioritization score, not an experimental label.")
    report.append("The tree regressor is used only to examine nonlinear feature sensitivity to this proxy score.")
    report.append("")
    report.append(f"Total records used: {len(X)}")
    report.append(f"Total groups: {len(unique_groups)}")
    report.append(f"Held-out R2 against proxy NSI: {test_r2:.4f}" if not np.isnan(test_r2) else "Held-out R2 against proxy NSI: undefined")
    report.append(f"Feature columns used: {', '.join(feature_cols)}")
    report.append("")
    report.append("Recommended manuscript wording:")
    report.append("A hierarchical proxy Nitrosative Susceptibility Index was computed from accessibility, chemical microenvironment, evolutionary conservation, and functional-context components. Tree-based modeling was used only for nonlinear sensitivity analysis, while residue-level rankings were reported as the primary output.")
    return "\n".join(report)


# Optional supervised classification using independent labels

def run_classification(df: pd.DataFrame, label_col: str) -> str:
    X, feature_cols, numeric_cols, categorical_cols = build_feature_table(df, label_col=label_col)
    y = pd.to_numeric(df[label_col], errors="coerce").astype("Int64")
    valid = y.notna()

    X = X.loc[valid].copy()
    y = y.loc[valid].astype(int).values
    df_valid = df.loc[valid].copy()
    groups = get_groups(df_valid)

    if len(np.unique(y)) < 2:
        raise ValueError(f"Label column {label_col} contains fewer than two classes.")

    unique_groups = np.unique(groups)
    if len(unique_groups) < 3:
        raise ValueError("At least three groups are recommended for group-aware validation.")

    model = Pipeline([
        ("preprocess", make_preprocessor(numeric_cols, categorical_cols)),
        ("model", make_classifier()),
    ])

    splitter = GroupShuffleSplit(n_splits=1, test_size=TEST_SIZE, random_state=RANDOM_STATE)
    train_idx, test_idx = next(splitter.split(X, y, groups=groups))

    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    groups_train = groups[train_idx]

    n_splits = min(N_SPLITS, len(np.unique(groups_train)))
    gkf = GroupKFold(n_splits=n_splits)
    cv_auc_scores = []
    cv_ap_scores = []

    for train_fold_idx, val_fold_idx in gkf.split(X_train, y_train, groups=groups_train):
        X_fold_train = X_train.iloc[train_fold_idx]
        X_fold_val = X_train.iloc[val_fold_idx]
        y_fold_train = y_train[train_fold_idx]
        y_fold_val = y_train[val_fold_idx]
        if len(np.unique(y_fold_val)) < 2 or len(np.unique(y_fold_train)) < 2:
            continue
        fold_model = Pipeline([
            ("preprocess", make_preprocessor(numeric_cols, categorical_cols)),
            ("model", make_classifier()),
        ])
        fold_model.fit(X_fold_train, y_fold_train)
        fold_proba = fold_model.predict_proba(X_fold_val)[:, 1]
        cv_auc_scores.append(roc_auc_score(y_fold_val, fold_proba))
        cv_ap_scores.append(average_precision_score(y_fold_val, fold_proba))

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    test_auc = roc_auc_score(y_test, y_proba) if len(np.unique(y_test)) > 1 else np.nan
    test_ap = average_precision_score(y_test, y_proba) if len(np.unique(y_test)) > 1 else np.nan
    save_permutation_importance(model, X_test, y_test, feature_cols, scoring="roc_auc" if len(np.unique(y_test)) > 1 else "accuracy")

    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(5.2, 4.4))
    plt.imshow(cm, interpolation="nearest")
    plt.title("Group-Held-Out Confusion Matrix")
    plt.xlabel("Predicted label")
    plt.ylabel("True label")
    plt.xticks([0, 1], ["Resistant", "Susceptible"], rotation=30, ha="right")
    plt.yticks([0, 1], ["Resistant", "Susceptible"])
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, str(cm[i, j]), ha="center", va="center")
    plt.tight_layout()
    plt.savefig(PLOT_CONFUSION_MATRIX, dpi=300)
    plt.close()

    if len(np.unique(y_test)) > 1:
        fpr, tpr, _ = roc_curve(y_test, y_proba)
        plt.figure(figsize=(6, 5))
        plt.plot(fpr, tpr, lw=2, label=f"AUC = {test_auc:.3f}")
        plt.plot([0, 1], [0, 1], linestyle="--", lw=1)
        plt.xlabel("False positive rate")
        plt.ylabel("True positive rate")
        plt.title("Group-Held-Out ROC Curve")
        plt.legend(loc="lower right")
        plt.tight_layout()
        plt.savefig(PLOT_ROC, dpi=300)
        plt.close()

        precision, recall, _ = precision_recall_curve(y_test, y_proba)
        plt.figure(figsize=(6, 5))
        plt.plot(recall, precision, lw=2, label=f"AP = {test_ap:.3f}")
        plt.xlabel("Recall")
        plt.ylabel("Precision")
        plt.title("Group-Held-Out Precision-Recall Curve")
        plt.legend(loc="lower left")
        plt.tight_layout()
        plt.savefig(PLOT_PR, dpi=300)
        plt.close()

    report = []
    report.append("NITROSATIVE SUSCEPTIBILITY CLASSIFICATION REPORT")
    report.append("=" * 60)
    report.append("Mode: supervised classification")
    report.append(f"Label column: {label_col}")
    report.append(f"Model: {'XGBoost' if XGBOOST_AVAILABLE else 'RandomForest'}")
    report.append(f"Total labeled records: {len(X)}")
    report.append(f"Total groups: {len(unique_groups)}")
    report.append(f"Training records: {len(X_train)}")
    report.append(f"Held-out test records: {len(X_test)}")
    report.append(f"Feature columns used: {', '.join(feature_cols)}")
    report.append("")
    report.append("Group-aware cross-validation on training data:")
    report.append(f"Mean ROC-AUC: {np.mean(cv_auc_scores):.4f}" if cv_auc_scores else "Mean ROC-AUC: undefined")
    report.append(f"Mean average precision: {np.mean(cv_ap_scores):.4f}" if cv_ap_scores else "Mean average precision: undefined")
    report.append("")
    report.append("Held-out group test performance:")
    report.append(f"ROC-AUC: {test_auc:.4f}" if not np.isnan(test_auc) else "ROC-AUC: undefined")
    report.append(f"Average precision: {test_ap:.4f}" if not np.isnan(test_ap) else "Average precision: undefined")
    report.append("")
    report.append(classification_report(y_test, y_pred, zero_division=0))
    report.append("")
    report.append("Important note: metrics are valid only if the label column represents independent curated or experimental labels.")
    return "\n".join(report)


# =============================================================================
# 6. MAIN
# =============================================================================
def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    input_file = find_input_file()
    print(f"\n[1/5] Loading feature matrix:\n  {input_file}")

    df = pd.read_csv(input_file)
    if df.empty:
        raise ValueError("The feature matrix is empty.")

    print(f"  Records loaded: {len(df)}")
    print(f"  Columns loaded: {len(df.columns)}")

    print("\n[2/5] Computing hierarchical proxy NSI ranking...")
    df_nsi = compute_hierarchical_nsi(df)
    residue_ranked = save_nsi_outputs(df_nsi)
    ablation_df = run_ablation_analysis(df_nsi)

    print(f"  Variant-level ranked sites saved: {OUTPUT_RANKED_NSI}")
    print(f"  Residue-level ranked sites saved: {OUTPUT_RESIDUE_RANKING}")
    print(f"  Component scores saved: {OUTPUT_COMPONENTS}")
    print(f"  Ablation summary saved: {OUTPUT_ABLATION}")

    print("\n[3/5] Checking whether supervised classification is appropriate...")
    label_col = choose_label_column(df_nsi)
    if label_col is not None:
        print(f"  Found curated/experimental label column: {label_col}")
        report = run_classification(df_nsi, label_col)
    else:
        print("  No curated binary label column found. Running tree-based NSI sensitivity mode.")
        report = run_nsi_regression(df_nsi)

    with OUTPUT_MODEL_REPORT.open("w", encoding="utf-8") as f:
        f.write(report)

    print("\n[4/5] Outputs saved:")
    print(f"  Model report:              {OUTPUT_MODEL_REPORT}")
    print(f"  Feature importance:        {OUTPUT_FEATURE_IMPORTANCE}")
    print(f"  NSI distribution plot:     {PLOT_NSI_DISTRIBUTION}")
    print(f"  Variant-level top plot:    {PLOT_TOP_VARIANT_SITES}")
    print(f"  Residue-level top plot:    {PLOT_TOP_RESIDUES}")
    print(f"  Component contribution:    {PLOT_COMPONENT_IMPORTANCE}")
    print(f"  Ablation plot:             {PLOT_ABLATION}")
    print(f"  Feature sensitivity plot:  {PLOT_FEATURE_IMPORTANCE}")
    if label_col is not None:
        print(f"  Confusion matrix:          {PLOT_CONFUSION_MATRIX}")
        print(f"  ROC curve:                 {PLOT_ROC}")
        print(f"  Precision-recall curve:    {PLOT_PR}")

    print("\n[5/5] Done.\n")


if __name__ == "__main__":
    main()
